### PR TITLE
Migrate to Koa v2 middleware signature

### PR DESCRIPTION
**Pull request by nfantone**
- Change middleware to accommodate to new Koa 2.0.0.
- Update unit tests.

### CODE REVIEW

**Comment by bishtawi** [comment]
+1

**Comment by Foxandxss** [comment]
I guess this would break koa 1 usage, right?

**Comment by nfantone** [comment]
You are right. Care to create a new branch and base the PR there? This is what most koa-\* plugins are doing.

**Comment by Foxandxss** [comment]
Will take a peek on the other libs and do the same thing.

**Comment by Foxandxss** [comment]
I created a new branch for it and released to npm.

Thanks.

**Comment by nfantone** [comment]
@Foxandxss Fantastic! Thanks.

**Pull request closed without merging**
