### PR TITLE
Refactoring with three goals in mind: readability, learn it and facilitate writing of more testing scenarios.

### PR DESCRIPTION
**Pull request by brunokrebs**
I have made a few changes on the main source code of this package and a few (lot?) of changes on the test structure. But both of them are quite simple.

First, about `index.js`, I have made the following changes:

1. Moved every single match to a function of its own (one for custom, one for paths, one for extensions and one for methods).
2. Tried to leave the export declaration as clean as possible, with a few comments to help the reader.

Now about the tests:

1. I have created a folder `scenarios` to hold different files that represent different sets of tests.
2. I have created a function, `runTests`, that encapsulated the logic to run these different tests.

The second step was taken to avoid repeating a lot of `app = koa()`, `app.use(...)` and etc.

I assure that no functionality was changed and only more and more tests were added. I'm willing to create a typescript definition on [DefinitelyTyped repository](https://github.com/DefinitelyTyped/DefinitelyTyped) to facilitate those who are using Typescript.

### CODE REVIEW

**Comment by Foxandxss** [comment]
Sounds like good changes mate. I will review tomorrow, it is getting late in here.

Could you please update travis to use latest node? It complains about ES6 stuff.

**Comment by brunokrebs** [comment]
If you want, @Foxandxss, we can schedule a quick meeting where I explain the changes that I made.

**Comment by Foxandxss** [comment]
What can I say, best PR of the year.

**Comment by Foxandxss** [comment]
No need, I saw what you did, absolutely fantastic.

**Pull request merged**
